version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    groups:
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        patterns:
          - "*"
